language: java
jdk: oraclejdk7

before_install: mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=5.0p -DbuildDate=2015-11-29
install: mvn clean install
sudo: false

notifications:
  email: false
  webhooks:
      urls: https://webhooks.gitter.im/e/b38a7fadad0c7821d365
      on_success: never
      on_failure: change
      on_start: never

deploy:
  skip_cleanup: true
  provider: script
  script: >-
            curl --ftp-create-dirs -T target/meditor.war -u $FTP_USER:$FTP_PASSWORD ftp://ftp-devel.mzk.cz/meditor/master/;
            curl -H "Content-Type: application/json" --data '{"docker_tag": "latest"}' -X POST https://registry.hub.docker.com/u/moravianlibrary/meditor/trigger/45687579-deca-4b2c-99ce-c14a03b07a00/