sudo: required
language: java
jdk: oraclejdk7
services:
  - docker

install:
  - mvn com.isomorphic:isc-maven-plugin:install -Dproduct=SMARTGWT -Dlicense=LGPL -DbuildNumber=5.0p -DbuildDate=2015-11-29
  - mkdir ~/.meditor && cp -r resources/xml/ ~/.meditor
script:
  - mvn clean install
  - cp target/meditor.war dockerfile/meditor/
  - docker build -t moravianlibrary/meditor dockerfile/meditor

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push moravianlibrary/meditor

notifications:
  email: false
  webhooks:
      urls: https://webhooks.gitter.im/e/b38a7fadad0c7821d365
      on_success: never
      on_failure: change
      on_start: never