/*
 * Metadata Editor
 * @author Jiri Kremser
 * 
 * 
 * 
 * Metadata Editor - Rich internet application for editing metadata.
 * Copyright (C) 2011  Jiri Kremser (kremser@mzk.cz)
 * Moravian Library in Brno
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

// TODO: Auto-generated Javadoc
/**
 * The Class BaseDateTypeClient.
 */
public class BaseDateTypeClient implements IsSerializable {

	/** The value. */
	protected String value;
	
	/** The encoding. */
	protected String encoding;
	
	/** The qualifier. */
	protected String qualifier;
	
	/** The point. */
	protected String point;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the encoding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEncoding() {
		return encoding;
	}

	/**
	 * Sets the value of the encoding property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setEncoding(String value) {
		this.encoding = value;
	}

	/**
	 * Gets the value of the qualifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQualifier() {
		return qualifier;
	}

	/**
	 * Sets the value of the qualifier property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setQualifier(String value) {
		this.qualifier = value;
	}

	/**
	 * Gets the value of the point property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPoint() {
		return point;
	}

	/**
	 * Sets the value of the point property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setPoint(String value) {
		this.point = value;
	}

}
