//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

public class BaseDateTypeClient implements IsSerializable {

	protected String value;
	protected String encoding;
	protected String qualifier;
	protected String point;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the encoding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEncoding() {
		return encoding;
	}

	/**
	 * Sets the value of the encoding property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setEncoding(String value) {
		this.encoding = value;
	}

	/**
	 * Gets the value of the qualifier property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getQualifier() {
		return qualifier;
	}

	/**
	 * Sets the value of the qualifier property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setQualifier(String value) {
		this.qualifier = value;
	}

	/**
	 * Gets the value of the point property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPoint() {
		return point;
	}

	/**
	 * Sets the value of the point property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setPoint(String value) {
		this.point = value;
	}

}
