/*
 * Metadata Editor
 * @author Jiri Kremser
 * 
 * 
 * 
 * Metadata Editor - Rich internet application for editing metadata.
 * Copyright (C) 2011  Jiri Kremser (kremser@mzk.cz)
 * Moravian Library in Brno
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.ArrayList;
import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.EnumerationAndChronologyType;
import cz.fi.muni.xkremser.editor.server.mods.StringPlusAuthority;
import cz.fi.muni.xkremser.editor.server.mods.StringPlusDisplayLabelPlusType;

// TODO: Auto-generated Javadoc
/**
 * The Class CopyInformationTypeClient.
 */
public class CopyInformationTypeClient implements IsSerializable {

	/** The form. */
	protected StringPlusAuthorityClient form;

	/** The sub location. */
	protected List<String> subLocation;

	/** The shelf locator. */
	protected List<String> shelfLocator;

	/** The electronic locator. */
	protected List<String> electronicLocator;

	/** The note. */
	protected List<StringPlusDisplayLabelPlusTypeClient> note;

	/** The enumeration and chronology. */
	protected List<EnumerationAndChronologyTypeClient> enumerationAndChronology;

	/**
	 * Gets the value of the form property.
	 * 
	 * @return possible object is {@link StringPlusAuthority }
	 * 
	 */
	public StringPlusAuthorityClient getForm() {
		return form;
	}

	/**
	 * Sets the value of the form property.
	 * 
	 * @param value
	 *          allowed object is {@link StringPlusAuthority }
	 * 
	 */
	public void setForm(StringPlusAuthorityClient value) {
		this.form = value;
	}

	/**
	 * Gets the value of the subLocation property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the subLocation property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubLocation().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * @return the sub location
	 */
	public List<String> getSubLocation() {
		if (subLocation == null) {
			subLocation = new ArrayList<String>();
		}
		return this.subLocation;
	}

	/**
	 * Gets the value of the shelfLocator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the shelfLocator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getShelfLocator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * @return the shelf locator
	 */
	public List<String> getShelfLocator() {
		if (shelfLocator == null) {
			shelfLocator = new ArrayList<String>();
		}
		return this.shelfLocator;
	}

	/**
	 * Gets the value of the electronicLocator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the electronicLocator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getElectronicLocator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * @return the electronic locator
	 */
	public List<String> getElectronicLocator() {
		if (electronicLocator == null) {
			electronicLocator = new ArrayList<String>();
		}
		return this.electronicLocator;
	}

	/**
	 * Gets the value of the note property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the note property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNote().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * 
	 * @return the note {@link StringPlusDisplayLabelPlusType }
	 */
	public List<StringPlusDisplayLabelPlusTypeClient> getNote() {
		if (note == null) {
			note = new ArrayList<StringPlusDisplayLabelPlusTypeClient>();
		}
		return this.note;
	}

	/**
	 * Gets the value of the enumerationAndChronology property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the enumerationAndChronology property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEnumerationAndChronology().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * 
	 * @return the enumeration and chronology {@link EnumerationAndChronologyType }
	 */
	public List<EnumerationAndChronologyTypeClient> getEnumerationAndChronology() {
		if (enumerationAndChronology == null) {
			enumerationAndChronology = new ArrayList<EnumerationAndChronologyTypeClient>();
		}
		return this.enumerationAndChronology;
	}

	/**
	 * Sets the sub location.
	 * 
	 * @param subLocation
	 *          the new sub location
	 */
	public void setSubLocation(List<String> subLocation) {
		this.subLocation = subLocation;
	}

	/**
	 * Sets the shelf locator.
	 * 
	 * @param shelfLocator
	 *          the new shelf locator
	 */
	public void setShelfLocator(List<String> shelfLocator) {
		this.shelfLocator = shelfLocator;
	}

	/**
	 * Sets the electronic locator.
	 * 
	 * @param electronicLocator
	 *          the new electronic locator
	 */
	public void setElectronicLocator(List<String> electronicLocator) {
		this.electronicLocator = electronicLocator;
	}

	/**
	 * Sets the note.
	 * 
	 * @param note
	 *          the new note
	 */
	public void setNote(List<StringPlusDisplayLabelPlusTypeClient> note) {
		this.note = note;
	}

	/**
	 * Sets the enumeration and chronology.
	 * 
	 * @param enumerationAndChronology
	 *          the new enumeration and chronology
	 */
	public void setEnumerationAndChronology(List<EnumerationAndChronologyTypeClient> enumerationAndChronology) {
		this.enumerationAndChronology = enumerationAndChronology;
	}

}
