//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.ArrayList;
import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.EnumerationAndChronologyType;
import cz.fi.muni.xkremser.editor.server.mods.StringPlusAuthority;
import cz.fi.muni.xkremser.editor.server.mods.StringPlusDisplayLabelPlusType;

public class CopyInformationTypeClient implements IsSerializable {

	protected StringPlusAuthorityClient form;
	protected List<String> subLocation;
	protected List<String> shelfLocator;
	protected List<String> electronicLocator;
	protected List<StringPlusDisplayLabelPlusTypeClient> note;
	protected List<EnumerationAndChronologyTypeClient> enumerationAndChronology;

	/**
	 * Gets the value of the form property.
	 * 
	 * @return possible object is {@link StringPlusAuthority }
	 * 
	 */
	public StringPlusAuthorityClient getForm() {
		return form;
	}

	/**
	 * Sets the value of the form property.
	 * 
	 * @param value
	 *          allowed object is {@link StringPlusAuthority }
	 * 
	 */
	public void setForm(StringPlusAuthorityClient value) {
		this.form = value;
	}

	/**
	 * Gets the value of the subLocation property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the subLocation property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSubLocation().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getSubLocation() {
		if (subLocation == null) {
			subLocation = new ArrayList<String>();
		}
		return this.subLocation;
	}

	/**
	 * Gets the value of the shelfLocator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the shelfLocator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getShelfLocator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getShelfLocator() {
		if (shelfLocator == null) {
			shelfLocator = new ArrayList<String>();
		}
		return this.shelfLocator;
	}

	/**
	 * Gets the value of the electronicLocator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the electronicLocator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getElectronicLocator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getElectronicLocator() {
		if (electronicLocator == null) {
			electronicLocator = new ArrayList<String>();
		}
		return this.electronicLocator;
	}

	/**
	 * Gets the value of the note property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the note property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getNote().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link StringPlusDisplayLabelPlusType }
	 * 
	 * 
	 */
	public List<StringPlusDisplayLabelPlusTypeClient> getNote() {
		if (note == null) {
			note = new ArrayList<StringPlusDisplayLabelPlusTypeClient>();
		}
		return this.note;
	}

	/**
	 * Gets the value of the enumerationAndChronology property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the enumerationAndChronology property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getEnumerationAndChronology().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link EnumerationAndChronologyType }
	 * 
	 * 
	 */
	public List<EnumerationAndChronologyTypeClient> getEnumerationAndChronology() {
		if (enumerationAndChronology == null) {
			enumerationAndChronology = new ArrayList<EnumerationAndChronologyTypeClient>();
		}
		return this.enumerationAndChronology;
	}

	public void setSubLocation(List<String> subLocation) {
		this.subLocation = subLocation;
	}

	public void setShelfLocator(List<String> shelfLocator) {
		this.shelfLocator = shelfLocator;
	}

	public void setElectronicLocator(List<String> electronicLocator) {
		this.electronicLocator = electronicLocator;
	}

	public void setNote(List<StringPlusDisplayLabelPlusTypeClient> note) {
		this.note = note;
	}

	public void setEnumerationAndChronology(List<EnumerationAndChronologyTypeClient> enumerationAndChronology) {
		this.enumerationAndChronology = enumerationAndChronology;
	}

}
