//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

public class ExtentTypeClient implements IsSerializable {

	protected String start;
	protected String end;
	protected String total;
	protected String list;
	protected String unit;

	/**
	 * Gets the value of the start property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStart() {
		return start;
	}

	/**
	 * Sets the value of the start property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setStart(String value) {
		this.start = value;
	}

	/**
	 * Gets the value of the end property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEnd() {
		return end;
	}

	/**
	 * Sets the value of the end property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setEnd(String value) {
		this.end = value;
	}

	/**
	 * Gets the value of the total property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTotal() {
		return total;
	}

	/**
	 * Sets the value of the total property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setTotal(String value) {
		this.total = value;
	}

	/**
	 * Gets the value of the list property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getList() {
		return list;
	}

	/**
	 * Sets the value of the list property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setList(String value) {
		this.list = value;
	}

	/**
	 * Gets the value of the unit property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * Sets the value of the unit property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setUnit(String value) {
		this.unit = value;
	}

}
