//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class HierarchicalGeographicTypeClient implements IsSerializable {
	protected List<String> extraterrestrialArea;
	protected List<String> continent;
	protected List<String> country;
	protected List<String> province;
	protected List<String> region;
	protected List<String> state;
	protected List<String> territory;
	protected List<String> county;
	protected List<String> city;
	protected List<String> citySection;

	public List<String> getExtraterrestrialArea() {
		return extraterrestrialArea;
	}

	public void setExtraterrestrialArea(List<String> extraterrestrialArea) {
		this.extraterrestrialArea = extraterrestrialArea;
	}

	public List<String> getContinent() {
		return continent;
	}

	public void setContinent(List<String> continent) {
		this.continent = continent;
	}

	public List<String> getCountry() {
		return country;
	}

	public void setCountry(List<String> country) {
		this.country = country;
	}

	public List<String> getProvince() {
		return province;
	}

	public void setProvince(List<String> province) {
		this.province = province;
	}

	public List<String> getRegion() {
		return region;
	}

	public void setRegion(List<String> region) {
		this.region = region;
	}

	public List<String> getState() {
		return state;
	}

	public void setState(List<String> state) {
		this.state = state;
	}

	public List<String> getTerritory() {
		return territory;
	}

	public void setTerritory(List<String> territory) {
		this.territory = territory;
	}

	public List<String> getCounty() {
		return county;
	}

	public void setCounty(List<String> county) {
		this.county = county;
	}

	public List<String> getCity() {
		return city;
	}

	public void setCity(List<String> city) {
		this.city = city;
	}

	public List<String> getCitySection() {
		return citySection;
	}

	public void setCitySection(List<String> citySection) {
		this.citySection = citySection;
	}

}
