/*
 * Metadata Editor
 * @author Jiri Kremser
 * 
 * 
 * 
 * Metadata Editor - Rich internet application for editing metadata.
 * Copyright (C) 2011  Jiri Kremser (kremser@mzk.cz)
 * Moravian Library in Brno
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

// TODO: Auto-generated Javadoc
/**
 * The Class HierarchicalGeographicTypeClient.
 */
public class HierarchicalGeographicTypeClient implements IsSerializable {
	
	/** The extraterrestrial area. */
	protected List<String> extraterrestrialArea;
	
	/** The continent. */
	protected List<String> continent;
	
	/** The country. */
	protected List<String> country;
	
	/** The province. */
	protected List<String> province;
	
	/** The region. */
	protected List<String> region;
	
	/** The state. */
	protected List<String> state;
	
	/** The territory. */
	protected List<String> territory;
	
	/** The county. */
	protected List<String> county;
	
	/** The city. */
	protected List<String> city;
	
	/** The city section. */
	protected List<String> citySection;
	
	/** The island. */
	protected List<String> island;
	
	/** The area. */
	protected List<String> area;

	/**
	 * Gets the island.
	 *
	 * @return the island
	 */
	public List<String> getIsland() {
		return island;
	}

	/**
	 * Sets the island.
	 *
	 * @param island the new island
	 */
	public void setIsland(List<String> island) {
		this.island = island;
	}

	/**
	 * Gets the area.
	 *
	 * @return the area
	 */
	public List<String> getArea() {
		return area;
	}

	/**
	 * Sets the area.
	 *
	 * @param area the new area
	 */
	public void setArea(List<String> area) {
		this.area = area;
	}

	/**
	 * Gets the extraterrestrial area.
	 *
	 * @return the extraterrestrial area
	 */
	public List<String> getExtraterrestrialArea() {
		return extraterrestrialArea;
	}

	/**
	 * Sets the extraterrestrial area.
	 *
	 * @param extraterrestrialArea the new extraterrestrial area
	 */
	public void setExtraterrestrialArea(List<String> extraterrestrialArea) {
		this.extraterrestrialArea = extraterrestrialArea;
	}

	/**
	 * Gets the continent.
	 *
	 * @return the continent
	 */
	public List<String> getContinent() {
		return continent;
	}

	/**
	 * Sets the continent.
	 *
	 * @param continent the new continent
	 */
	public void setContinent(List<String> continent) {
		this.continent = continent;
	}

	/**
	 * Gets the country.
	 *
	 * @return the country
	 */
	public List<String> getCountry() {
		return country;
	}

	/**
	 * Sets the country.
	 *
	 * @param country the new country
	 */
	public void setCountry(List<String> country) {
		this.country = country;
	}

	/**
	 * Gets the province.
	 *
	 * @return the province
	 */
	public List<String> getProvince() {
		return province;
	}

	/**
	 * Sets the province.
	 *
	 * @param province the new province
	 */
	public void setProvince(List<String> province) {
		this.province = province;
	}

	/**
	 * Gets the region.
	 *
	 * @return the region
	 */
	public List<String> getRegion() {
		return region;
	}

	/**
	 * Sets the region.
	 *
	 * @param region the new region
	 */
	public void setRegion(List<String> region) {
		this.region = region;
	}

	/**
	 * Gets the state.
	 *
	 * @return the state
	 */
	public List<String> getState() {
		return state;
	}

	/**
	 * Sets the state.
	 *
	 * @param state the new state
	 */
	public void setState(List<String> state) {
		this.state = state;
	}

	/**
	 * Gets the territory.
	 *
	 * @return the territory
	 */
	public List<String> getTerritory() {
		return territory;
	}

	/**
	 * Sets the territory.
	 *
	 * @param territory the new territory
	 */
	public void setTerritory(List<String> territory) {
		this.territory = territory;
	}

	/**
	 * Gets the county.
	 *
	 * @return the county
	 */
	public List<String> getCounty() {
		return county;
	}

	/**
	 * Sets the county.
	 *
	 * @param county the new county
	 */
	public void setCounty(List<String> county) {
		this.county = county;
	}

	/**
	 * Gets the city.
	 *
	 * @return the city
	 */
	public List<String> getCity() {
		return city;
	}

	/**
	 * Sets the city.
	 *
	 * @param city the new city
	 */
	public void setCity(List<String> city) {
		this.city = city;
	}

	/**
	 * Gets the city section.
	 *
	 * @return the city section
	 */
	public List<String> getCitySection() {
		return citySection;
	}

	/**
	 * Sets the city section.
	 *
	 * @param citySection the new city section
	 */
	public void setCitySection(List<String> citySection) {
		this.citySection = citySection;
	}

}
