//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class LanguageTypeClient implements IsSerializable {

	protected List<LanguageTypeClient.LanguageTermClient> languageTerm;
	protected String objectPart;

	public List<LanguageTypeClient.LanguageTermClient> getLanguageTerm() {
		return this.languageTerm;
	}

	public void setLanguageTerm(List<LanguageTypeClient.LanguageTermClient> languageTerm) {
		this.languageTerm = languageTerm;
	}

	public String getObjectPart() {
		return objectPart;
	}

	public void setObjectPart(String value) {
		this.objectPart = value;
	}

	public static class LanguageTermClient implements IsSerializable {

		protected String value;
		protected String authority;
		protected CodeOrTextClient type;

		public String getValue() {
			return value;
		}

		public void setValue(String value) {
			this.value = value;
		}

		public String getAuthority() {
			return authority;
		}

		public void setAuthority(String value) {
			this.authority = value;
		}

		public CodeOrTextClient getType() {
			return type;
		}

		public void setType(CodeOrTextClient value) {
			this.type = value;
		}

	}

}
