//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.HoldingSimpleType;

public class LocationTypeClient implements IsSerializable {

	protected List<PhysicalLocationTypeClient> physicalLocation;
	protected List<String> shelfLocator;
	protected List<UrlTypeClient> url;
	protected HoldingSimpleTypeClient holdingSimple;
	protected ExtensionTypeClient holdingExternal;

	public List<PhysicalLocationTypeClient> getPhysicalLocation() {
		return this.physicalLocation;
	}

	public List<String> getShelfLocator() {
		return this.shelfLocator;
	}

	public List<UrlTypeClient> getUrl() {
		return this.url;
	}

	public void setPhysicalLocation(List<PhysicalLocationTypeClient> physicalLocation) {
		this.physicalLocation = physicalLocation;
	}

	public void setShelfLocator(List<String> shelfLocator) {
		this.shelfLocator = shelfLocator;
	}

	public void setUrl(List<UrlTypeClient> url) {
		this.url = url;
	}

	/**
	 * Gets the value of the holdingSimple property.
	 * 
	 * @return possible object is {@link HoldingSimpleType }
	 * 
	 */
	public HoldingSimpleTypeClient getHoldingSimple() {
		return holdingSimple;
	}

	/**
	 * Sets the value of the holdingSimple property.
	 * 
	 * @param value
	 *          allowed object is {@link HoldingSimpleType }
	 * 
	 */
	public void setHoldingSimple(HoldingSimpleTypeClient value) {
		this.holdingSimple = value;
	}

	/**
	 * Gets the value of the holdingExternal property.
	 * 
	 * @return possible object is {@link ExtensionType }
	 * 
	 */
	public ExtensionTypeClient getHoldingExternal() {
		return holdingExternal;
	}

	/**
	 * Sets the value of the holdingExternal property.
	 * 
	 * @param value
	 *          allowed object is {@link ExtensionType }
	 * 
	 */
	public void setHoldingExternal(ExtensionTypeClient value) {
		this.holdingExternal = value;
	}

}
