//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class ModsTypeClient implements IsSerializable {
	protected List<TitleInfoTypeClient> titleInfo;
	protected List<NameTypeClient> name;
	protected List<TypeOfResourceTypeClient> typeOfResource;
	protected List<GenreTypeClient> genre;
	protected List<OriginInfoTypeClient> originInfo;
	protected List<LanguageTypeClient> language;
	protected List<PhysicalDescriptionTypeClient> physicalDescription;
	protected List<AbstractTypeClient> abstrac;
	protected List<TableOfContentsTypeClient> tableOfContents;
	protected List<TargetAudienceTypeClient> targetAudience;
	protected List<NoteTypeClient> note;
	protected List<SubjectTypeClient> subject;
	protected List<ClassificationTypeClient> classification;
	protected List<RelatedItemTypeClient> relatedItem;
	protected List<IdentifierTypeClient> identifier;
	protected List<LocationTypeClient> location;
	protected List<AccessConditionTypeClient> accessCondition;
	protected List<PartTypeClient> part;
	protected List<ExtensionTypeClient> extension;
	protected List<RecordInfoTypeClient> recordInfo;
	protected String id;
	protected String version;

	public List<TitleInfoTypeClient> getTitleInfo() {
		return titleInfo;
	}

	public void setTitleInfo(List<TitleInfoTypeClient> titleInfo) {
		this.titleInfo = titleInfo;
	}

	public List<NameTypeClient> getName() {
		return name;
	}

	public void setName(List<NameTypeClient> name) {
		this.name = name;
	}

	public List<TypeOfResourceTypeClient> getTypeOfResource() {
		return typeOfResource;
	}

	public void setTypeOfResource(List<TypeOfResourceTypeClient> typeOfResource) {
		this.typeOfResource = typeOfResource;
	}

	public List<GenreTypeClient> getGenre() {
		return genre;
	}

	public void setGenre(List<GenreTypeClient> genre) {
		this.genre = genre;
	}

	public List<OriginInfoTypeClient> getOriginInfo() {
		return originInfo;
	}

	public void setOriginInfo(List<OriginInfoTypeClient> originInfo) {
		this.originInfo = originInfo;
	}

	public List<LanguageTypeClient> getLanguage() {
		return language;
	}

	public void setLanguage(List<LanguageTypeClient> language) {
		this.language = language;
	}

	public List<PhysicalDescriptionTypeClient> getPhysicalDescription() {
		return physicalDescription;
	}

	public void setPhysicalDescription(List<PhysicalDescriptionTypeClient> physicalDescription) {
		this.physicalDescription = physicalDescription;
	}

	public List<AbstractTypeClient> getAbstrac() {
		return abstrac;
	}

	public void setAbstrac(List<AbstractTypeClient> abstrac) {
		this.abstrac = abstrac;
	}

	public List<TableOfContentsTypeClient> getTableOfContents() {
		return tableOfContents;
	}

	public void setTableOfContents(List<TableOfContentsTypeClient> tableOfContents) {
		this.tableOfContents = tableOfContents;
	}

	public List<TargetAudienceTypeClient> getTargetAudience() {
		return targetAudience;
	}

	public void setTargetAudience(List<TargetAudienceTypeClient> targetAudience) {
		this.targetAudience = targetAudience;
	}

	public List<NoteTypeClient> getNote() {
		return note;
	}

	public void setNote(List<NoteTypeClient> note) {
		this.note = note;
	}

	public List<SubjectTypeClient> getSubject() {
		return subject;
	}

	public void setSubject(List<SubjectTypeClient> subject) {
		this.subject = subject;
	}

	public List<ClassificationTypeClient> getClassification() {
		return classification;
	}

	public void setClassification(List<ClassificationTypeClient> classification) {
		this.classification = classification;
	}

	public List<RelatedItemTypeClient> getRelatedItem() {
		return relatedItem;
	}

	public void setRelatedItem(List<RelatedItemTypeClient> relatedItem) {
		this.relatedItem = relatedItem;
	}

	public List<IdentifierTypeClient> getIdentifier() {
		return identifier;
	}

	public void setIdentifier(List<IdentifierTypeClient> identifier) {
		this.identifier = identifier;
	}

	public List<LocationTypeClient> getLocation() {
		return location;
	}

	public void setLocation(List<LocationTypeClient> location) {
		this.location = location;
	}

	public List<AccessConditionTypeClient> getAccessCondition() {
		return accessCondition;
	}

	public void setAccessCondition(List<AccessConditionTypeClient> accessCondition) {
		this.accessCondition = accessCondition;
	}

	public List<PartTypeClient> getPart() {
		return part;
	}

	public void setPart(List<PartTypeClient> part) {
		this.part = part;
	}

	public List<ExtensionTypeClient> getExtension() {
		return extension;
	}

	public void setExtension(List<ExtensionTypeClient> extension) {
		this.extension = extension;
	}

	public List<RecordInfoTypeClient> getRecordInfo() {
		return recordInfo;
	}

	public void setRecordInfo(List<RecordInfoTypeClient> recordInfo) {
		this.recordInfo = recordInfo;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

}
