//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class NameTypeClient implements IsSerializable {

	protected List<NamePartTypeClient> namePart;
	protected List<String> displayForm;
	protected List<String> affiliation;
	protected List<RoleTypeClient> role;
	protected List<String> description;
	protected NameTypeAttributeClient type;
	protected String id;
	protected String authority;
	protected String xlink;
	protected String xmlLang;
	protected String lang;
	protected String script;
	protected String transliteration;

	public List<NamePartTypeClient> getNamePart() {
		return namePart;
	}

	public void setNamePart(List<NamePartTypeClient> namePart) {
		this.namePart = namePart;
	}

	public List<String> getDisplayForm() {
		return displayForm;
	}

	public void setDisplayForm(List<String> displayForm) {
		this.displayForm = displayForm;
	}

	public List<String> getAffiliation() {
		return affiliation;
	}

	public void setAffiliation(List<String> affiliation) {
		this.affiliation = affiliation;
	}

	public List<RoleTypeClient> getRole() {
		return role;
	}

	public void setRole(List<RoleTypeClient> role) {
		this.role = role;
	}

	public List<String> getDescription() {
		return description;
	}

	public void setDescription(List<String> description) {
		this.description = description;
	}

	public NameTypeAttributeClient getType() {
		return type;
	}

	public void setType(NameTypeAttributeClient type) {
		this.type = type;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAuthority() {
		return authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	public String getXlink() {
		return xlink;
	}

	public void setXlink(String xlink) {
		this.xlink = xlink;
	}

	public String getXmlLang() {
		return xmlLang;
	}

	public void setXmlLang(String xmlLang) {
		this.xmlLang = xmlLang;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public String getScript() {
		return script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public String getTransliteration() {
		return transliteration;
	}

	public void setTransliteration(String transliteration) {
		this.transliteration = transliteration;
	}

}
