//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class OriginInfoTypeClient implements IsSerializable {

	protected List<PlaceTypeClient> place;
	protected List<String> publisher;
	protected List<DateTypeClient> dateIssued;
	protected List<DateTypeClient> dateCreated;
	protected List<DateTypeClient> dateCaptured;
	protected List<DateTypeClient> dateValid;
	protected List<DateTypeClient> dateModified;
	protected List<DateTypeClient> copyrightDate;
	protected List<DateOtherTypeClient> dateOther;
	protected List<String> edition;
	protected List<String> issuance;
	protected List<StringPlusAuthorityClient> frequency;
	protected String xmlLang;
	protected String lang;
	protected String script;
	protected String transliteration;

	public List<PlaceTypeClient> getPlace() {
		return place;
	}

	public void setPlace(List<PlaceTypeClient> place) {
		this.place = place;
	}

	public List<String> getPublisher() {
		return publisher;
	}

	public void setPublisher(List<String> publisher) {
		this.publisher = publisher;
	}

	public List<DateTypeClient> getDateIssued() {
		return dateIssued;
	}

	public void setDateIssued(List<DateTypeClient> dateIssued) {
		this.dateIssued = dateIssued;
	}

	public List<DateTypeClient> getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(List<DateTypeClient> dateCreated) {
		this.dateCreated = dateCreated;
	}

	public List<DateTypeClient> getDateCaptured() {
		return dateCaptured;
	}

	public void setDateCaptured(List<DateTypeClient> dateCaptured) {
		this.dateCaptured = dateCaptured;
	}

	public List<DateTypeClient> getDateValid() {
		return dateValid;
	}

	public void setDateValid(List<DateTypeClient> dateValid) {
		this.dateValid = dateValid;
	}

	public List<DateTypeClient> getDateModified() {
		return dateModified;
	}

	public void setDateModified(List<DateTypeClient> dateModified) {
		this.dateModified = dateModified;
	}

	public List<DateTypeClient> getCopyrightDate() {
		return copyrightDate;
	}

	public void setCopyrightDate(List<DateTypeClient> copyrightDate) {
		this.copyrightDate = copyrightDate;
	}

	public List<DateOtherTypeClient> getDateOther() {
		return dateOther;
	}

	public void setDateOther(List<DateOtherTypeClient> dateOther) {
		this.dateOther = dateOther;
	}

	public List<String> getEdition() {
		return edition;
	}

	public void setEdition(List<String> edition) {
		this.edition = edition;
	}

	public List<String> getIssuance() {
		return issuance;
	}

	public void setIssuance(List<String> issuance) {
		this.issuance = issuance;
	}

	public List<StringPlusAuthorityClient> getFrequency() {
		return frequency;
	}

	public void setFrequency(List<StringPlusAuthorityClient> frequency) {
		this.frequency = frequency;
	}

	public String getXmlLang() {
		return xmlLang;
	}

	public void setXmlLang(String xmlLang) {
		this.xmlLang = xmlLang;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public String getScript() {
		return script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public String getTransliteration() {
		return transliteration;
	}

	public void setTransliteration(String transliteration) {
		this.transliteration = transliteration;
	}

}
