//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class PartTypeClient implements IsSerializable {

	// TODO: Object to Serializable
	protected List<DetailTypeClient> detail;
	protected List<ExtentTypeClient> extent;
	protected List<BaseDateTypeClient> date;
	protected List<String> text;
	protected String id;
	protected String type;
	protected String order;

	public List<DetailTypeClient> getDetail() {
		return detail;
	}

	public void setDetail(List<DetailTypeClient> detail) {
		this.detail = detail;
	}

	public List<ExtentTypeClient> getExtent() {
		return extent;
	}

	public void setExtent(List<ExtentTypeClient> extent) {
		this.extent = extent;
	}

	public List<BaseDateTypeClient> getDate() {
		return date;
	}

	public void setDate(List<BaseDateTypeClient> date) {
		this.date = date;
	}

	public List<String> getText() {
		return text;
	}

	public void setText(List<String> text) {
		this.text = text;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getOrder() {
		return order;
	}

	public void setOrder(String order) {
		this.order = order;
	}
}
