/*
 * Metadata Editor
 * @author Jiri Kremser
 * 
 * 
 * 
 * Metadata Editor - Rich internet application for editing metadata.
 * Copyright (C) 2011  Jiri Kremser (kremser@mzk.cz)
 * Moravian Library in Brno
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

// TODO: Auto-generated Javadoc
/**
 * The Class PartTypeClient.
 */
public class PartTypeClient implements IsSerializable {

	// TODO: Object to Serializable
	/** The detail. */
	protected List<DetailTypeClient> detail;
	
	/** The extent. */
	protected List<ExtentTypeClient> extent;
	
	/** The date. */
	protected List<BaseDateTypeClient> date;
	
	/** The text. */
	protected List<String> text;
	
	/** The id. */
	protected String id;
	
	/** The type. */
	protected String type;
	
	/** The order. */
	protected String order;

	/**
	 * Gets the detail.
	 *
	 * @return the detail
	 */
	public List<DetailTypeClient> getDetail() {
		return detail;
	}

	/**
	 * Sets the detail.
	 *
	 * @param detail the new detail
	 */
	public void setDetail(List<DetailTypeClient> detail) {
		this.detail = detail;
	}

	/**
	 * Gets the extent.
	 *
	 * @return the extent
	 */
	public List<ExtentTypeClient> getExtent() {
		return extent;
	}

	/**
	 * Sets the extent.
	 *
	 * @param extent the new extent
	 */
	public void setExtent(List<ExtentTypeClient> extent) {
		this.extent = extent;
	}

	/**
	 * Gets the date.
	 *
	 * @return the date
	 */
	public List<BaseDateTypeClient> getDate() {
		return date;
	}

	/**
	 * Sets the date.
	 *
	 * @param date the new date
	 */
	public void setDate(List<BaseDateTypeClient> date) {
		this.date = date;
	}

	/**
	 * Gets the text.
	 *
	 * @return the text
	 */
	public List<String> getText() {
		return text;
	}

	/**
	 * Sets the text.
	 *
	 * @param text the new text
	 */
	public void setText(List<String> text) {
		this.text = text;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Gets the order.
	 *
	 * @return the order
	 */
	public String getOrder() {
		return order;
	}

	/**
	 * Sets the order.
	 *
	 * @param order the new order
	 */
	public void setOrder(String order) {
		this.order = order;
	}
}
