//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class PhysicalDescriptionTypeClient implements IsSerializable {

	protected List<StringPlusAuthorityPlusTypeClient> form;
	protected List<String> reformattingQuality;
	protected List<String> internetMediaType;
	protected List<String> extent;
	protected List<String> digitalOrigin;
	protected List<NoteTypeClient> note;

	protected String xmlLang;
	protected String lang;
	protected String script;
	protected String transliteration;

	public List<StringPlusAuthorityPlusTypeClient> getForm() {
		return form;
	}

	public void setForm(List<StringPlusAuthorityPlusTypeClient> form) {
		this.form = form;
	}

	public List<String> getReformattingQuality() {
		return reformattingQuality;
	}

	public void setReformattingQuality(List<String> reformattingQuality) {
		this.reformattingQuality = reformattingQuality;
	}

	public List<String> getInternetMediaType() {
		return internetMediaType;
	}

	public void setInternetMediaType(List<String> internetMediaType) {
		this.internetMediaType = internetMediaType;
	}

	public List<String> getExtent() {
		return extent;
	}

	public void setExtent(List<String> extent) {
		this.extent = extent;
	}

	public List<String> getDigitalOrigin() {
		return digitalOrigin;
	}

	public void setDigitalOrigin(List<String> digitalOrigin) {
		this.digitalOrigin = digitalOrigin;
	}

	public List<NoteTypeClient> getNote() {
		return note;
	}

	public void setNote(List<NoteTypeClient> note) {
		this.note = note;
	}

	public String getXmlLang() {
		return xmlLang;
	}

	public void setXmlLang(String xmlLang) {
		this.xmlLang = xmlLang;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public String getScript() {
		return script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public String getTransliteration() {
		return transliteration;
	}

	public void setTransliteration(String transliteration) {
		this.transliteration = transliteration;
	}

}
