//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

public enum PlaceAuthorityClient implements IsSerializable {

	MARCGAC("marcgac"), MARCCOUNTRY("marccountry"), ISO_3166("iso3166");
	private final String value;

	PlaceAuthorityClient(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static PlaceAuthorityClient fromValue(String v) {
		for (PlaceAuthorityClient c : PlaceAuthorityClient.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
