//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

public class RecordInfoTypeClient implements IsSerializable {

	protected List<StringPlusAuthorityPlusLanguageClient> recordContentSource;
	protected List<DateTypeClient> recordCreationDate;
	protected List<DateTypeClient> recordChangeDate;
	protected List<RecordIdentifierClient> recordIdentifier;
	protected List<LanguageTypeClient> languageOfCataloging;
	protected List<String> recordOrigin;
	protected List<StringPlusAuthorityClient> descriptionStandard;
	protected String xmlLang;
	protected String lang;
	protected String script;
	protected String transliteration;

	public List<StringPlusAuthorityPlusLanguageClient> getRecordContentSource() {
		return recordContentSource;
	}

	public void setRecordContentSource(List<StringPlusAuthorityPlusLanguageClient> recordContentSource) {
		this.recordContentSource = recordContentSource;
	}

	public List<DateTypeClient> getRecordCreationDate() {
		return recordCreationDate;
	}

	public void setRecordCreationDate(List<DateTypeClient> recordCreationDate) {
		this.recordCreationDate = recordCreationDate;
	}

	public List<DateTypeClient> getRecordChangeDate() {
		return recordChangeDate;
	}

	public void setRecordChangeDate(List<DateTypeClient> recordChangeDate) {
		this.recordChangeDate = recordChangeDate;
	}

	public List<RecordIdentifierClient> getRecordIdentifier() {
		return recordIdentifier;
	}

	public void setRecordIdentifier(List<RecordIdentifierClient> recordIdentifier) {
		this.recordIdentifier = recordIdentifier;
	}

	public List<LanguageTypeClient> getLanguageOfCataloging() {
		return languageOfCataloging;
	}

	public void setLanguageOfCataloging(List<LanguageTypeClient> languageOfCataloging) {
		this.languageOfCataloging = languageOfCataloging;
	}

	public List<String> getRecordOrigin() {
		return recordOrigin;
	}

	public void setRecordOrigin(List<String> recordOrigin) {
		this.recordOrigin = recordOrigin;
	}

	public List<StringPlusAuthorityClient> getDescriptionStandard() {
		return descriptionStandard;
	}

	public void setDescriptionStandard(List<StringPlusAuthorityClient> descriptionStandard) {
		this.descriptionStandard = descriptionStandard;
	}

	public String getXmlLang() {
		return xmlLang;
	}

	public void setXmlLang(String xmlLang) {
		this.xmlLang = xmlLang;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public String getScript() {
		return script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public String getTransliteration() {
		return transliteration;
	}

	public void setTransliteration(String transliteration) {
		this.transliteration = transliteration;
	}

	public static class RecordIdentifierClient implements IsSerializable {

		protected String value;
		protected String source;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *          allowed object is {@link String }
		 * 
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the source property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSource() {
			return source;
		}

		/**
		 * Sets the value of the source property.
		 * 
		 * @param value
		 *          allowed object is {@link String }
		 * 
		 */
		public void setSource(String value) {
			this.source = value;
		}

	}

}
