/*
 * Metadata Editor
 * @author Jiri Kremser
 * 
 * 
 * 
 * Metadata Editor - Rich internet application for editing metadata.
 * Copyright (C) 2011  Jiri Kremser (kremser@mzk.cz)
 * Moravian Library in Brno
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.CodeOrText;
import cz.fi.muni.xkremser.editor.server.mods.RoleType;

// TODO: Auto-generated Javadoc
/**
 * The Class RoleTypeClient.
 */
public class RoleTypeClient implements IsSerializable {

	/** The role term. */
	protected List<RoleTypeClient.RoleTermClient> roleTerm;

	/**
	 * Gets the value of the roleTerm property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the roleTerm property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRoleTerm().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * 
	 * @return the role term {@link RoleType.RoleTerm }
	 */
	public List<RoleTypeClient.RoleTermClient> getRoleTerm() {
		return this.roleTerm;
	}

	/**
	 * Sets the role term.
	 * 
	 * @param roleTerm
	 *          the new role term
	 */
	public void setRoleTerm(List<RoleTypeClient.RoleTermClient> roleTerm) {
		this.roleTerm = roleTerm;
	}

	/**
	 * if it is a code: 100, 110, 111, 700, 710, 711 $4. If it is text:100, 110,
	 * 700, 710 $e.
	 * 
	 * 
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.loc.gov/mods/v3>stringPlusAuthority">
	 *       &lt;attribute name="type" type="{http://www.loc.gov/mods/v3}codeOrText" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class RoleTermClient extends StringPlusAuthorityClient implements IsSerializable {

		/** The type. */
		protected CodeOrTextClient type;

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link CodeOrText }
		 * 
		 */
		public CodeOrTextClient getType() {
			return type;
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *          allowed object is {@link CodeOrText }
		 * 
		 */
		public void setType(CodeOrTextClient value) {
			this.type = value;
		}

	}

}
