//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

public class StringPlusAuthorityPlusEditionClient extends StringPlusAuthorityClient implements IsSerializable {

	protected String edition;

	/**
	 * Gets the value of the edition property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEdition() {
		return edition;
	}

	/**
	 * Sets the value of the edition property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setEdition(String value) {
		this.edition = value;
	}

}
