//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

public class StringPlusAuthorityPlusTypePlusLanguageClient extends StringPlusAuthorityPlusLanguageClient implements IsSerializable {

	protected String type;

	public String getType() {
		return type;
	}

	public void setType(String value) {
		this.type = value;
	}

}
