//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.PlaceAuthority;

public class SubjectTypeClient implements IsSerializable {

	protected List<String> topic;
	protected List<String> geographic;
	protected List<DateTypeClient> temporal;
	protected List<TitleInfoTypeClient> titleInfo;
	protected List<NameTypeClient> name;
	protected List<GeographicCodeClient> geographicCode;
	protected List<HierarchicalGeographicTypeClient> hierarchicalGeographic;
	protected List<CartographicsClient> cartographics;
	protected List<String> occupation;
	protected List<String> genre;

	protected String id;
	protected String authority;
	protected String type;
	protected String xlink;
	protected String xmlLang;
	protected String lang;
	protected String script;
	protected String transliteration;

	public List<String> getTopic() {
		return topic;
	}

	public void setTopic(List<String> topic) {
		this.topic = topic;
	}

	public List<String> getGeographic() {
		return geographic;
	}

	public void setGeographic(List<String> geographic) {
		this.geographic = geographic;
	}

	public List<DateTypeClient> getTemporal() {
		return temporal;
	}

	public void setTemporal(List<DateTypeClient> temporal) {
		this.temporal = temporal;
	}

	public List<TitleInfoTypeClient> getTitleInfo() {
		return titleInfo;
	}

	public void setTitleInfo(List<TitleInfoTypeClient> titleInfo) {
		this.titleInfo = titleInfo;
	}

	public List<NameTypeClient> getName() {
		return name;
	}

	public void setName(List<NameTypeClient> name) {
		this.name = name;
	}

	public List<GeographicCodeClient> getGeographicCode() {
		return geographicCode;
	}

	public void setGeographicCode(List<GeographicCodeClient> geographicCode) {
		this.geographicCode = geographicCode;
	}

	public List<HierarchicalGeographicTypeClient> getHierarchicalGeographic() {
		return hierarchicalGeographic;
	}

	public void setHierarchicalGeographic(List<HierarchicalGeographicTypeClient> hierarchicalGeographic) {
		this.hierarchicalGeographic = hierarchicalGeographic;
	}

	public List<CartographicsClient> getCartographics() {
		return cartographics;
	}

	public void setCartographics(List<CartographicsClient> cartographics) {
		this.cartographics = cartographics;
	}

	public List<String> getOccupation() {
		return occupation;
	}

	public void setOccupation(List<String> occupation) {
		this.occupation = occupation;
	}

	public List<String> getGenre() {
		return genre;
	}

	public void setGenre(List<String> genre) {
		this.genre = genre;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getAuthority() {
		return authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getXlink() {
		return xlink;
	}

	public void setXlink(String xlink) {
		this.xlink = xlink;
	}

	public String getXmlLang() {
		return xmlLang;
	}

	public void setXmlLang(String xmlLang) {
		this.xmlLang = xmlLang;
	}

	public String getLang() {
		return lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public String getScript() {
		return script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	public String getTransliteration() {
		return transliteration;
	}

	public void setTransliteration(String transliteration) {
		this.transliteration = transliteration;
	}

	public static class CartographicsClient implements IsSerializable {

		protected String scale;
		protected String projection;
		protected List<String> coordinates;

		/**
		 * Gets the value of the scale property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getScale() {
			return scale;
		}

		/**
		 * Sets the value of the scale property.
		 * 
		 * @param value
		 *          allowed object is {@link String }
		 * 
		 */
		public void setScale(String value) {
			this.scale = value;
		}

		/**
		 * Gets the value of the projection property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getProjection() {
			return projection;
		}

		/**
		 * Sets the value of the projection property.
		 * 
		 * @param value
		 *          allowed object is {@link String }
		 * 
		 */
		public void setProjection(String value) {
			this.projection = value;
		}

		public List<String> getCoordinates() {
			return this.coordinates;
		}

		public void setCoordinates(List<String> coordinates) {
			this.coordinates = coordinates;
		}

	}

	/**
	 * 043
	 * 
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="authority" type="{http://www.loc.gov/mods/v3}placeAuthority" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	public static class GeographicCodeClient implements IsSerializable {

		protected String value;
		protected PlaceAuthorityClient authority;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *          allowed object is {@link String }
		 * 
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the authority property.
		 * 
		 * @return possible object is {@link PlaceAuthority }
		 * 
		 */
		public PlaceAuthorityClient getAuthority() {
			return authority;
		}

		/**
		 * Sets the value of the authority property.
		 * 
		 * @param value
		 *          allowed object is {@link PlaceAuthority }
		 * 
		 */
		public void setAuthority(PlaceAuthorityClient value) {
			this.authority = value;
		}

	}

}
