//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.Yes;

public class TypeOfResourceTypeClient implements IsSerializable {

	protected String value;
	protected YesClient collection;
	protected YesClient manuscript;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *          allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the collection property.
	 * 
	 * @return possible object is {@link Yes }
	 * 
	 */
	public YesClient getCollection() {
		return collection;
	}

	/**
	 * Sets the value of the collection property.
	 * 
	 * @param value
	 *          allowed object is {@link Yes }
	 * 
	 */
	public void setCollection(YesClient value) {
		this.collection = value;
	}

	/**
	 * Gets the value of the manuscript property.
	 * 
	 * @return possible object is {@link Yes }
	 * 
	 */
	public YesClient getManuscript() {
		return manuscript;
	}

	/**
	 * Sets the value of the manuscript property.
	 * 
	 * @param value
	 *          allowed object is {@link Yes }
	 * 
	 */
	public void setManuscript(YesClient value) {
		this.manuscript = value;
	}

}
