
package org.fedora.api;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Fedora-API-A-Service", targetNamespace = "http://www.fedora.info/definitions/1/0/api/", wsdlLocation = "file:/home/freon/kramerius4/fedora-api/src/wsdl/APIA.wsdl")
public class FedoraAPIAService
    extends Service
{

    private final static URL FEDORAAPIASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.fedora.api.FedoraAPIAService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.fedora.api.FedoraAPIAService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/freon/kramerius4/fedora-api/src/wsdl/APIA.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/freon/kramerius4/fedora-api/src/wsdl/APIA.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FEDORAAPIASERVICE_WSDL_LOCATION = url;
    }

    public FedoraAPIAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FedoraAPIAService() {
        super(FEDORAAPIASERVICE_WSDL_LOCATION, new QName("http://www.fedora.info/definitions/1/0/api/", "Fedora-API-A-Service"));
    }

    /**
     * 
     * @return
     *     returns FedoraAPIA
     */
    @WebEndpoint(name = "Fedora-API-A-Service-HTTP-Port")
    public FedoraAPIA getFedoraAPIAServiceHTTPPort() {
        return super.getPort(new QName("http://www.fedora.info/definitions/1/0/api/", "Fedora-API-A-Service-HTTP-Port"), FedoraAPIA.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FedoraAPIA
     */
    @WebEndpoint(name = "Fedora-API-A-Service-HTTP-Port")
    public FedoraAPIA getFedoraAPIAServiceHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fedora.info/definitions/1/0/api/", "Fedora-API-A-Service-HTTP-Port"), FedoraAPIA.class, features);
    }

}
