
package com.abby.recognitionserver3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RSSoapServiceSoap", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RSSoapServiceSoap {


    /**
     * 
     * @param stub
     */
    @WebMethod(operationName = "DoNothingMethod", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/DoNothingMethod")
    @RequestWrapper(localName = "DoNothingMethod", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.DoNothingMethod")
    @ResponseWrapper(localName = "DoNothingMethodResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.DoNothingMethodResponse")
    public void doNothingMethod(
        @WebParam(name = "stub", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        StubFormatsCollection stub);

    /**
     * 
     * @param stub
     */
    @WebMethod(operationName = "DoNothingMethod2", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/DoNothingMethod2")
    @RequestWrapper(localName = "DoNothingMethod2", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.DoNothingMethod2")
    @ResponseWrapper(localName = "DoNothingMethod2Response", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.DoNothingMethod2Response")
    public void doNothingMethod2(
        @WebParam(name = "stub", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        StubDocumentAttributesCollection stub);

    /**
     * 
     * @param serverLocation
     * @return
     *     returns com.abby.recognitionserver3.ArrayOfString
     */
    @WebMethod(operationName = "GetWorkflows", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/GetWorkflows")
    @WebResult(name = "GetWorkflowsResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    @RequestWrapper(localName = "GetWorkflows", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.GetWorkflows")
    @ResponseWrapper(localName = "GetWorkflowsResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.GetWorkflowsResponse")
    public ArrayOfString getWorkflows(
        @WebParam(name = "serverLocation", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String serverLocation);

    /**
     * 
     * @param workflowName
     * @param location
     * @param file
     * @return
     *     returns com.abby.recognitionserver3.XmlResult
     */
    @WebMethod(operationName = "ProcessFile", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/ProcessFile")
    @WebResult(name = "ProcessFileResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    @RequestWrapper(localName = "ProcessFile", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.ProcessFile")
    @ResponseWrapper(localName = "ProcessFileResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.ProcessFileResponse")
    public XmlResult processFile(
        @WebParam(name = "location", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String location,
        @WebParam(name = "workflowName", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String workflowName,
        @WebParam(name = "file", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        FileContainer file);

    /**
     * 
     * @param workflowName
     * @param location
     * @return
     *     returns com.abby.recognitionserver3.XmlTicket
     */
    @WebMethod(operationName = "CreateTicket", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/CreateTicket")
    @WebResult(name = "CreateTicketResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    @RequestWrapper(localName = "CreateTicket", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.CreateTicket")
    @ResponseWrapper(localName = "CreateTicketResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.CreateTicketResponse")
    public XmlTicket createTicket(
        @WebParam(name = "location", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String location,
        @WebParam(name = "workflowName", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String workflowName);

    /**
     * 
     * @param workflowName
     * @param ticket
     * @param location
     * @return
     *     returns com.abby.recognitionserver3.XmlResult
     */
    @WebMethod(operationName = "ProcessTicket", action = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml/ProcessTicket")
    @WebResult(name = "ProcessTicketResult", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
    @RequestWrapper(localName = "ProcessTicket", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.ProcessTicket")
    @ResponseWrapper(localName = "ProcessTicketResponse", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", className = "com.abby.recognitionserver3.ProcessTicketResponse")
    public XmlResult processTicket(
        @WebParam(name = "location", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String location,
        @WebParam(name = "workflowName", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        String workflowName,
        @WebParam(name = "ticket", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml")
        XmlTicket ticket);

}
