
package com.abby.recognitionserver3;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RSSoapService", targetNamespace = "http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", wsdlLocation = "http://195.113.155.161/Recognition3WS/RSSoapService.asmx?WSDL")
public class RSSoapService
    extends Service
{

    private final static URL RSSOAPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.abby.recognitionserver3.RSSoapService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.abby.recognitionserver3.RSSoapService.class.getResource(".");
            url = new URL(baseUrl, "http://195.113.155.161/Recognition3WS/RSSoapService.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://195.113.155.161/Recognition3WS/RSSoapService.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RSSOAPSERVICE_WSDL_LOCATION = url;
    }

    public RSSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RSSoapService() {
        super(RSSOAPSERVICE_WSDL_LOCATION, new QName("http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", "RSSoapService"));
    }

    /**
     * 
     * @return
     *     returns RSSoapServiceSoap
     */
    @WebEndpoint(name = "RSSoapServiceSoap")
    public RSSoapServiceSoap getRSSoapServiceSoap() {
        return super.getPort(new QName("http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", "RSSoapServiceSoap"), RSSoapServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RSSoapServiceSoap
     */
    @WebEndpoint(name = "RSSoapServiceSoap")
    public RSSoapServiceSoap getRSSoapServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.abbyy.com/RecognitionServer3_xml/RecognitionServer3.xml", "RSSoapServiceSoap"), RSSoapServiceSoap.class, features);
    }

}
