/*
 * Metadata Editor
 * @author Jiri Kremser
 * 
 * 
 * 
 * Metadata Editor - Rich internet application for editing metadata.
 * Copyright (C) 2011  Jiri Kremser (kremser@mzk.cz)
 * Moravian Library in Brno
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * 
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.13 at 05:02:55 odp. CET 
//

package cz.fi.muni.xkremser.editor.client.mods;

import java.util.List;

import com.google.gwt.user.client.rpc.IsSerializable;

import cz.fi.muni.xkremser.editor.server.mods.PlaceTermType;

// TODO: Auto-generated Javadoc
/**
 * The Class PlaceTypeClient.
 */
public class PlaceTypeClient
        implements IsSerializable {

    /** The place term. */
    protected List<PlaceTermTypeClient> placeTerm;

    /**
     * Gets the value of the placeTerm property.
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the placeTerm property.
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
	 * getPlaceTerm().add(newItem);
	 * </pre>
     * <p>
     * Objects of the following type(s) are allowed in the list
     * 
     * @return the place term {@link PlaceTermType }
     */
    public List<PlaceTermTypeClient> getPlaceTerm() {
        return this.placeTerm;
    }

    /**
     * Sets the place term.
     * 
     * @param placeTerm
     *        the new place term
     */
    public void setPlaceTerm(List<PlaceTermTypeClient> placeTerm) {
        this.placeTerm = placeTerm;
    }

}
